site_name: PyFLP
site_url: https://pyflp.rtfd.io/
site_description: Library to read and edit FL Studio project (.flp) files
site_author: demberto
repo_url: https://github.com/demberto/PyFLP/
copyright: (c) demberto 2021
nav:
  - Overview: index.md
  - Getting Started: getting-started.md
  - FLP Format: flp-format.md
  - How does it work?: how-does-it-work.md
  - Issues: https://github.com/demberto/PyFLP/issues
theme: readthedocs
markdown_extensions:
  - smarty
  - admonition
